/*
 * Generated by scripts/make_icons.py from app/brand.py — do not edit by hand.
 *
 * The mark: a wave over a rule, stacked like an equals sign. It inherits
 * `currentColor`, so it takes the accent on a light surface and the lighter
 * accent in dark mode without a second copy.
 */
export function Logo({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 32 32"
      className={className}
      role="img"
      aria-hidden="true"
      fill="currentColor"
    >
      <path
        d="M2.500 10.200C3.625 10.200 4.750 11.582 5.875 13.100C7.000 14.618 8.125 16.000 9.250 16.000C10.375 16.000 11.500 14.618 12.625 13.100C13.750 11.582 14.875 10.200 16.000 10.200C17.125 10.200 18.250 11.582 19.375 13.100C20.500 14.618 21.625 16.000 22.750 16.000C23.875 16.000 25.000 14.618 26.125 13.100C27.250 11.582 28.375 10.200 29.500 10.200"
        fill="none"
        stroke="currentColor"
        strokeWidth="3.0"
        strokeLinecap="butt"
      />
      <rect x="2.5" y="20.3" width="27.0" height="3.0" />
    </svg>
  );
}
