"""notes.json → two HTML variants (§10). Deterministic, offline, no LLM.

Direction follows the **summary** language, not the meeting's: a Hebrew meeting
summarised into English produces an LTR document.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from app import meta
from app.asr.models import ASR_LANGUAGE
from app.clock import parse_iso
from app.log import get
from app.pipeline.artifacts import up_to_date
from app.pipeline.context import StageContext
from app.pipeline.stages.summarize import load_notes, notes_path

log = get(__name__)

UI_NAME = "summary.html"
EMAIL_NAME = "summary.email.html"

RTL_LANGUAGES = frozenset({"he", "ar", "fa", "ur"})

LABELS: dict[str, dict[str, str]] = {
    "en": {
        "tldr": "TL;DR",
        "topics": "Topics",
        "decisions": "Decisions",
        "actions": "Action items",
        "questions": "Open questions",
        "risks": "Risks",
        "due": "due",
        "none": "Nothing recorded.",
        "footer": "Generated by Upshot from the recording on this machine.",
        "duration": "min",
    },
    "he": {
        "tldr": "תקציר",
        "topics": "נושאים",
        "decisions": "החלטות",
        "actions": "משימות",
        "questions": "שאלות פתוחות",
        "risks": "סיכונים",
        "due": "עד",
        "none": "לא נרשם דבר.",
        "footer": "הופק על ידי Upshot מההקלטה במחשב הזה.",
        "duration": "דק׳",
    },
}


def direction_for(language: str) -> str:
    return "rtl" if language.split("-")[0] in RTL_LANGUAGES else "ltr"


@dataclass(frozen=True)
class Rendered:
    ui: str
    email: str


def meta_line(meeting: dict[str, Any], labels: dict[str, str]) -> str:
    parts: list[str] = []
    started = meeting.get("started_at")
    if started:
        try:
            parts.append(parse_iso(str(started)).strftime("%Y-%m-%d %H:%M"))
        except ValueError:
            parts.append(str(started))
    duration = meeting.get("duration_s")
    if duration:
        parts.append(f"{int(duration) // 60} {labels['duration']}")
    return " · ".join(parts)


#: Model-authored HTML goes straight into a page the user opens, so the two things that
#: turn a document into code come out first. Everything else — structure, styling,
#: tables, inline CSS — is left exactly as written, because that is the whole point.
_SCRIPT = re.compile(r"<script\b.*?</script\s*>", re.IGNORECASE | re.DOTALL)
_HANDLER = re.compile(r"\son[a-z]+\s*=\s*(\"[^\"]*\"|'[^']*'|[^\s>]+)", re.IGNORECASE)


def sanitize(html: str) -> str:
    return _HANDLER.sub("", _SCRIPT.sub("", html))


def render_free(notes: dict[str, Any], *, language: str) -> Rendered:
    """Free-form: the prompt wrote the document, so nothing here relays it out."""
    body = sanitize(str(notes.get("summary_html", "")))
    direction = direction_for(language)
    page = f'<div dir="{direction}" lang="{language}" class="ma-free">{body}</div>'
    return Rendered(ui=page, email=page)


def output_paths(folder: Path) -> tuple[Path, Path]:
    return Path(folder) / UI_NAME, Path(folder) / EMAIL_NAME


def plaintext(notes: dict[str, Any], language: str) -> str:
    """A text/plain alternative for the email, from whatever HTML the prompt produced.

    Crude on purpose: tags out, entities in, blank lines collapsed. There is no structure
    left to walk — that was the point of removing the schema — so there is nothing
    cleverer to do than strip the markup.
    """
    import html as html_module

    body = sanitize(str(notes.get("summary_html", "")))
    body = re.sub(r"<(br|/p|/div|/h[1-6]|/li|/tr)\s*>", "\n", body, flags=re.IGNORECASE)
    text = html_module.unescape(re.sub(r"<[^>]+>", "", body))
    lines = [line.strip() for line in text.splitlines()]
    return "\n".join(line for line in lines if line) + "\n"


def run(ctx: StageContext) -> None:
    folder = ctx.folder
    source = notes_path(folder)
    ui_path, email_path = output_paths(folder)
    if not ctx.force and up_to_date(ui_path, [source]) and up_to_date(email_path, [source]):
        log.info("summary HTML is current; skipping")
        return
    if not source.exists():
        raise FileNotFoundError(f"{source} is missing — run the summarize stage first")

    notes = load_notes(folder)
    language = ctx.meeting.summary_language or ctx.config.summary_language
    if language == "auto":
        language = ctx.meeting.language or ASR_LANGUAGE
    rendered = render_free(notes, language=language)
    ui_path.write_text(rendered.ui, encoding="utf-8")
    email_path.write_text(rendered.email, encoding="utf-8")
    # The searchable copy (D61): search and the assistant read the summary from here.
    ctx.dao.index_summary(ctx.meeting.id, plaintext(notes, language))
    meta.mirror(ctx.refresh(), summary_language=language, rendered=True)
    ctx.metrics.update({"summary_language": language, "dir": direction_for(language)})
    log.info("rendered %s (%s)", ui_path.name, direction_for(language))


def backfill_search(dao: Any) -> int:
    """Copy the summary of every meeting that has none in the search index yet.

    Meetings summarized before summaries were searchable (2026-09-26) have only their
    files. Each is read once: a meeting with no summary gets an empty copy, which marks it
    as checked. Returns how many summaries were found.
    """
    found = 0
    for meeting in dao.meetings_without_summary_text():
        text = ""
        try:
            if notes_path(Path(meeting.folder)).exists():
                text = plaintext(load_notes(Path(meeting.folder)), meeting.language or "")
        except (OSError, ValueError) as exc:
            log.warning("could not read the summary of %s for search: %s", meeting.id, exc)
        dao.index_summary(meeting.id, text)
        found += bool(text.strip())
    return found
