"""notes.json → two HTML variants (§10). Deterministic, offline, no LLM.

Direction follows the **summary** language, not the meeting's: a Hebrew meeting
summarised into English produces an LTR document.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from app import meta, paths
from app.clock import parse_iso
from app.log import get
from app.pipeline.artifacts import up_to_date
from app.pipeline.context import StageContext
from app.pipeline.stages.summarize import load_notes, notes_path

log = get(__name__)

UI_NAME = "summary.html"
EMAIL_NAME = "summary.email.html"

RTL_LANGUAGES = frozenset({"he", "ar", "fa", "ur"})

LABELS: dict[str, dict[str, str]] = {
    "en": {
        "tldr": "TL;DR",
        "topics": "Topics",
        "decisions": "Decisions",
        "actions": "Action items",
        "questions": "Open questions",
        "risks": "Risks",
        "due": "due",
        "none": "Nothing recorded.",
        "footer": "Generated by Meeting Agent from the recording on this machine.",
        "duration": "min",
    },
    "he": {
        "tldr": "תקציר",
        "topics": "נושאים",
        "decisions": "החלטות",
        "actions": "משימות",
        "questions": "שאלות פתוחות",
        "risks": "סיכונים",
        "due": "עד",
        "none": "לא נרשם דבר.",
        "footer": "הופק על ידי Meeting Agent מההקלטה במחשב הזה.",
        "duration": "דק׳",
    },
}


def direction_for(language: str) -> str:
    return "rtl" if language.split("-")[0] in RTL_LANGUAGES else "ltr"


def labels_for(language: str) -> dict[str, str]:
    return LABELS.get(language.split("-")[0], LABELS["en"])


def template_dir() -> Path:
    return paths.resource("templates")


def stylesheet() -> str:
    return (template_dir() / "_email.css").read_text(encoding="utf-8")


@dataclass(frozen=True)
class Rendered:
    ui: str
    email: str


def _environment() -> Any:
    from jinja2 import Environment, FileSystemLoader, select_autoescape

    env = Environment(
        loader=FileSystemLoader(str(template_dir())),
        autoescape=select_autoescape(["html", "j2"]),
        trim_blocks=False,
        lstrip_blocks=False,
        keep_trailing_newline=True,
    )
    return env


def meta_line(meeting: dict[str, Any], labels: dict[str, str]) -> str:
    parts: list[str] = []
    started = meeting.get("started_at")
    if started:
        try:
            parts.append(parse_iso(str(started)).strftime("%Y-%m-%d %H:%M"))
        except ValueError:
            parts.append(str(started))
    duration = meeting.get("duration_s")
    if duration:
        parts.append(f"{int(duration) // 60} {labels['duration']}")
    return " · ".join(parts)


def render_html(
    notes: dict[str, Any],
    *,
    language: str,
    meeting: dict[str, Any] | None = None,
) -> Rendered:
    """One template, two passes: a styled page and a CSS-inlined email body."""
    env = _environment()
    template = env.get_template("summary.html.j2")
    labels = labels_for(language)
    context = {
        "notes": notes,
        "lang": language,
        "dir": direction_for(language),
        "labels": labels,
        "css": stylesheet(),
        "meta_line": meta_line(meeting or {}, labels),
    }
    ui = template.render(**context, include_style=True)
    email_source = template.render(**context, include_style=True)
    email = inline_css(email_source)
    return Rendered(ui=ui, email=email)


def inline_css(html: str) -> str:
    """premailer inlines every rule; Gmail's handling of ``<style>`` is unreliable."""
    from premailer import Premailer

    inliner = Premailer(
        html,
        base_url=None,
        remove_classes=False,
        keep_style_tags=False,
        strip_important=False,
        disable_validation=True,
        disable_leftover_css=True,
        # `text-align: start` is logical; premailer would mirror it into an
        # `align="start"` attribute, which is not a legal value for that attribute.
        disable_basic_attributes=["align"],
        cssutils_logging_level=50,
    )
    return str(inliner.transform())


def plaintext(notes: dict[str, Any], language: str) -> str:
    """The ``text/plain`` alternative — a mail client that shows no HTML still reads."""
    labels = labels_for(language)
    lines = [str(notes.get("title", "")), ""]
    lines.append(labels["tldr"])
    lines.extend(f"- {line}" for line in notes.get("tldr", []))
    for topic in notes.get("topics", []):
        lines.extend(["", str(topic.get("heading", ""))])
        lines.extend(f"- {point}" for point in topic.get("points", []))
    if notes.get("decisions"):
        lines.extend(["", labels["decisions"]])
        for decision in notes["decisions"]:
            who = decision.get("who_decided", "")
            lines.append(f"- {who} {decision.get('what', '')}".strip())
    if notes.get("action_items"):
        lines.extend(["", labels["actions"]])
        for item in notes["action_items"]:
            due = f" ({labels['due']} {item['due']})" if item.get("due") else ""
            lines.append(f"- {item.get('who', '')}: {item.get('what', '')}{due}")
    lines.extend(["", labels["footer"]])
    return "\n".join(lines) + "\n"


def output_paths(folder: Path) -> tuple[Path, Path]:
    return Path(folder) / UI_NAME, Path(folder) / EMAIL_NAME


def run(ctx: StageContext) -> None:
    folder = ctx.folder
    source = notes_path(folder)
    ui_path, email_path = output_paths(folder)
    if up_to_date(ui_path, [source]) and up_to_date(email_path, [source]):
        log.info("summary HTML is current; skipping")
        return
    if not source.exists():
        raise FileNotFoundError(f"{source} is missing — run the summarize stage first")

    notes = load_notes(folder)
    language = ctx.meeting.summary_language or ctx.config.summary_language
    if language == "auto":
        language = ctx.meeting.language or ctx.config.default_language
    rendered = render_html(notes, language=language, meeting=ctx.meeting.as_dict())
    ui_path.write_text(rendered.ui, encoding="utf-8")
    email_path.write_text(rendered.email, encoding="utf-8")
    meta.mirror(ctx.refresh(), summary_language=language, rendered=True)
    ctx.metrics.update({"summary_language": language, "dir": direction_for(language)})
    log.info("rendered %s (%s)", ui_path.name, direction_for(language))
