"""Generate every icon asset from the one definition in :mod:`app.brand`.

    python3 scripts/make_icons.py

Writes, all of them committed:

    packaging/icon.ico              the .exe and installer icon (PyInstaller picks
                                    it up automatically if it exists)
    frontend/public/favicon.svg     the browser tab, light and dark
    frontend/public/favicon.ico     the fallback for browsers that ignore SVG
    frontend/src/components/Logo.tsx  the mark inside the app, as currentColor

Re-run it after touching ``app/brand.py``. Nothing here is generated at build
time on purpose: the frontend build must not depend on a Python toolchain, and a
.ico that only exists on the machine that packaged the release is how an
installer ends up shipping the default blank icon.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app import brand  # noqa: E402

#: The accent, from frontend/src/tokens.css. Restated rather than parsed: these
#: are the two values the icon is allowed to be, and a silent change to either
#: should be a visible change to this file.
LIGHT = "#0f6f68"
DARK = "#3dbdb0"
LIGHT_RGB = (0x0F, 0x6F, 0x68)

#: Windows asks for all of these; leaving out 16 makes Explorer downscale 32 and
#: the wave turns to mush in exactly the place it is looked at most.
ICO_SIZES = (16, 24, 32, 48, 64, 128, 256)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"  {path.relative_to(ROOT)}")


def write_ico(path: Path, sizes: tuple[int, ...]) -> None:
    """Each size rendered at its own scale, not resampled from one big image."""
    images = [brand.render(s, LIGHT_RGB) for s in sizes]
    path.parent.mkdir(parents=True, exist_ok=True)
    largest, *rest = sorted(images, key=lambda im: im.size[0], reverse=True)
    largest.save(path, format="ICO", sizes=[im.size for im in images], append_images=rest)
    print(f"  {path.relative_to(ROOT)}  ({', '.join(str(s) for s in sizes)})")


def logo_component() -> str:
    rx0, ry0, rx1, ry1 = brand.rule_box()
    rw, rh = rx1 - rx0, ry1 - ry0
    return f"""/*
 * Generated by scripts/make_icons.py from app/brand.py — do not edit by hand.
 *
 * The mark: a wave over a rule, stacked like an equals sign. It inherits
 * `currentColor`, so it takes the accent on a light surface and the lighter
 * accent in dark mode without a second copy.
 */
export function Logo({{ className }}: {{ className?: string }}) {{
  return (
    <svg
      viewBox="0 0 32 32"
      className={{className}}
      role="img"
      aria-hidden="true"
      fill="currentColor"
    >
      <path
        d="{brand.wave_path()}"
        fill="none"
        stroke="currentColor"
        strokeWidth="{brand.WEIGHT}"
        strokeLinecap="butt"
      />
      <rect x="{rx0}" y="{ry0}" width="{rw}" height="{rh}" />
    </svg>
  );
}}
"""


def main() -> int:
    print("writing icon assets")
    write_ico(ROOT / "packaging" / "icon.ico", ICO_SIZES)
    write(ROOT / "frontend" / "public" / "favicon.svg", brand.svg_document(LIGHT, DARK))
    write_ico(ROOT / "frontend" / "public" / "favicon.ico", (16, 32, 48))
    write(ROOT / "frontend" / "src" / "components" / "Logo.tsx", logo_component())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
