; Per-user install, no admin prompt (SECURITY-AND-AUTH.md section 10 step 1).
;
; packaging\build.ps1 passes the version and commit: ISCC /DAppVersion=... /DAppCommit=...
; Keep this file ASCII: Inno reads a script without a BOM as the ANSI code page.
#define AppName "Upshot"
#ifndef AppVersion
  #define AppVersion "0.0.0"
#endif
#ifndef AppCommit
  #define AppCommit "unknown"
#endif
#define AppExe "upshot.exe"
; The running app's single-instance mutex (app/instance.py MUTEX_NAME).
#define AppMutex "Local\upshot"

[Setup]
; Never change the AppId: it is how an upgrade finds the installed copy.
AppId={{6F1B7C2E-4A8D-4E57-9C1D-3B2A9E0F5D11}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher=AM Consulting
AppPublisherURL=https://www.amconsultingai.com
VersionInfoVersion={#AppVersion}
VersionInfoDescription={#AppName} installer ({#AppCommit})
DefaultDirName={localappdata}\Programs\Upshot
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
OutputDir=..\dist
OutputBaseFilename=Upshot-{#AppVersion}-Setup
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
; Setup.exe's own icon. The installed app gets the same mark from the .exe, which
; PyInstaller stamps with this file (see packaging/upshot.spec); both are generated
; by scripts/make_icons.py.
SetupIconFile=icon.ico
; Upshot's own artwork, signed "powered by AM Consulting" at the foot of the panel and in
; the bottom bar of every page ([Messages] BeveledLabel). Generated by
; scripts/make_installer_art.py; Inno picks the size closest to the screen's scaling.
WizardImageFile=wizard-100.bmp,wizard-150.bmp,wizard-200.bmp
WizardSmallImageFile=wizard-small-100.bmp,wizard-small-150.bmp,wizard-small-200.bmp
UninstallDisplayIcon={app}\{#AppExe}
#ifdef Sign
; build.ps1 -Sign defines the "upshot" sign tool (packaging\sign.ps1): Setup and the
; uninstaller Inno generates are both signed.
SignTool=upshot
SignedUninstaller=yes
#endif
; A running copy holds its files open; ask it to close rather than failing half-way.
CloseApplications=yes

[Messages]
BeveledLabel=Powered by AM Consulting

[Files]
Source: "..\dist\upshot\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{userprograms}\{#AppName}"; Filename: "{app}\{#AppExe}"
; Always: Upshot notices meetings only while it runs (product owner, 2026-09-27: no
; "Select Additional Tasks" page; starting at sign-in and the model download are not asked).
; Windows' Startup apps (Task Manager, or Settings > Apps > Startup) can turn it off.
; --background: at sign-in Upshot starts in the tray without opening its window
; (app/window.py); every other start opens it.
Name: "{userstartup}\{#AppName}"; Filename: "{app}\{#AppExe}"; Parameters: "--background"

[Run]
; --setup-again: first-run setup opens after every install, on the saved choices (D69).
Filename: "{app}\{#AppExe}"; Parameters: "--bootstrap --setup-again"; StatusMsg: "Preparing first run..."; Flags: runhidden waituntilterminated
Filename: "{app}\{#AppExe}"; Description: "Launch {#AppName}"; Flags: nowait postinstall skipifsilent

; User data (meetings, recordings, settings, the speech model) lives in
; %LOCALAPPDATA%\upshot, outside {app}, so the uninstaller leaves it alone. It only
; offers to remove the speech model and GPU libraries (see [Code]).

[Code]
{ The speech model (and, with a suitable NVIDIA GPU, the CUDA libraries) is fetched
  during the install by "upshot.exe --prepare" (app/prepare.py), which does the work and
  the checks; this page only shows the progress file it writes.
  A download that fails or is stopped never fails the install: the app fetches a
  missing model before the first transcription, and runs on the CPU without the GPU
  libraries. }

const
  { Polls (200 ms each) without a new report before the download counts as dead: 2 minutes. }
  StalePolls = 600;

  { The least physical memory Upshot installs on (product owner, 2026-09-27): 12 GB. The
    CPU speech model peaks at about 4.4 GB on a 100-second clip (measured, build 19), and
    an 8 GB machine ran out of memory with Windows and a browser beside it. A PC sold as
    "12 GB" reports a little less (graphics memory is taken out), so the bar is 11.5 GB of
    what Windows reports. /NORAMCHECK=1 skips it: the test sandboxes top out near 10 GB. }
  MinRamMB = 11776;

type
  TMemoryStatusEx = record
    dwLength: Cardinal;
    dwMemoryLoad: Cardinal;
    ullTotalPhys: Int64;
    ullAvailPhys: Int64;
    ullTotalPageFile: Int64;
    ullAvailPageFile: Int64;
    ullTotalVirtual: Int64;
    ullAvailVirtual: Int64;
    ullAvailExtendedVirtual: Int64;
  end;

function GlobalMemoryStatusEx(var Buffer: TMemoryStatusEx): Boolean;
  external 'GlobalMemoryStatusEx@kernel32.dll stdcall';

var
  PreparePage: TOutputProgressWizardPage;
  PrepareNote: String;

function TotalRamMB: Int64;
var
  Status: TMemoryStatusEx;
begin
  Status.dwLength := 64;
  if GlobalMemoryStatusEx(Status) then
    Result := Status.ullTotalPhys div (1024 * 1024)
  else
    Result := -1;
end;

function HasSwitch(const Switch: String): Boolean;
var
  I: Integer;
begin
  Result := False;
  for I := 1 to ParamCount do
    if CompareText(ParamStr(I), Switch) = 0 then
      Result := True;
end;

function RamCheckSkipped: Boolean;
begin
  Result := HasSwitch('/NORAMCHECK=1');
end;

{ The download is no longer a choice in the wizard. A silent install that must not
  download (the Sandbox runner's jobs) passes /NOMODEL=1. }
function ModelDownloadSkipped: Boolean;
begin
  Result := HasSwitch('/NOMODEL=1');
end;

{ Before anything is copied: refuse a machine without the memory to transcribe. }
function InitializeSetup: Boolean;
var
  Ram: Int64;
  Gb: String;
begin
  Result := True;
  Ram := TotalRamMB;
  Log('Physical memory: ' + IntToStr(Ram) + ' MB (minimum ' + IntToStr(MinRamMB) + ' MB)');
  if RamCheckSkipped then begin
    Log('Memory check skipped (/NORAMCHECK=1)');
    Exit;
  end;
  if (Ram > 0) and (Ram < MinRamMB) then begin
    Gb := Format('%.1f', [Ram / 1024.0]);
    SuppressibleMsgBox('{#AppName} needs a computer with at least 12 GB of memory to transcribe meetings on it.' + #13#10#13#10 +
      'This computer has ' + Gb + ' GB, so {#AppName} will not be installed.', mbCriticalError, MB_OK, IDOK);
    Result := False;
  end;
end;

{ Upshot runs in the tray with no window, so neither CloseApplications nor the
  uninstaller can ask it to close: job 022 found the uninstaller leaving 57 files and a
  running upshot.exe behind while reporting success. First "upshot.exe --quit"
  (app/instance.py), so a meeting being recorded is closed properly; once its
  single-instance mutex has gone, or after 10 seconds, stop what is left outright. /T takes
  its child processes (a notification being shown) with it. }
procedure StopUpshot;
var
  Exe: String;
  ResultCode, I: Integer;
begin
  Exe := ExpandConstant('{app}\{#AppExe}');
  if CheckForMutexes('{#AppMutex}') and FileExists(Exe) then begin
    Log('Upshot is running; asking it to quit.');
    Exec(Exe, '--quit', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    I := 0;
    while CheckForMutexes('{#AppMutex}') and (I < 50) do begin
      Sleep(200);
      I := I + 1;
    end;
    if I < 50 then
      Log('Upshot quit.')
    else
      Log('Upshot did not quit within 10 seconds.');
  end;
  if Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /T /IM {#AppExe}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then begin
    { 0: stopped; 128: none was running }
    Log('taskkill {#AppExe}: exit ' + IntToStr(ResultCode));
    if ResultCode = 0 then
      Sleep(1500);
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  { An upgrade replaces upshot.exe, which a running copy holds open. }
  StopUpshot;
  Result := '';
end;

procedure InitializeWizard;
begin
  PreparePage := CreateOutputProgressPage('Getting {#AppName} ready to transcribe',
    '{#AppName} transcribes on this computer, so it needs its speech model. This is a one-time download.');
end;

function ReadValue(const Lines: TArrayOfString; const Key: String): String;
var
  I: Integer;
begin
  Result := '';
  for I := 0 to GetArrayLength(Lines) - 1 do
    if Pos(Key + '=', Lines[I]) = 1 then begin
      Result := Copy(Lines[I], Length(Key) + 2, MaxInt);
      Exit;
    end;
end;

function StageHint(const Stage: String): String;
begin
  if Stage = 'gpu' then
    Result := 'NVIDIA cuBLAS and cuDNN, so transcription runs on your graphics card.'
  else
    Result := 'Hebrew and English speech recognition (ivrit-ai), from Hugging Face.';
end;

procedure RunPrepare;
var
  ProgressFile, Params, Stage, State, Code, Error, Tick, LastTick: String;
  Lines: TArrayOfString;
  ResultCode, Percent, Quiet: Integer;
begin
  ProgressFile := ExpandConstant('{tmp}\prepare-progress.txt');
  Params := '--prepare --progress-file "' + ProgressFile + '"';
  Log('Running upshot.exe ' + Params);
  { As the signed-in user, not an elevated one: the model belongs in their profile. }
  if not ExecAsOriginalUser(ExpandConstant('{app}\{#AppExe}'), Params, '', SW_HIDE, ewNoWait, ResultCode) then begin
    Log('Could not start the download: ' + SysErrorMessage(ResultCode));
    PrepareNote := 'The speech model was not downloaded. {#AppName} downloads it before your first transcription.';
    Exit;
  end;
  PreparePage.SetText('Starting the download...', StageHint('model'));
  PreparePage.SetProgress(0, 100);
  PreparePage.Show;
  State := '';
  Stage := 'model';
  Error := '';
  LastTick := '';
  Quiet := 0;
  try
    repeat
      Sleep(200);
      Quiet := Quiet + 1;
      if LoadStringsFromFile(ProgressFile, Lines) then begin
        Tick := ReadValue(Lines, 'tick');
        if Tick <> LastTick then begin
          LastTick := Tick;
          Quiet := 0;
        end;
        Stage := ReadValue(Lines, 'stage');
        State := ReadValue(Lines, 'state');
        Code := ReadValue(Lines, 'code');
        Error := ReadValue(Lines, 'error');
        Percent := StrToIntDef(ReadValue(Lines, 'percent'), 0);
        PreparePage.SetText(ReadValue(Lines, 'text'), StageHint(Stage));
        PreparePage.SetProgress(Percent, 100);
        if (State = 'failed') or (State = 'cancelled') or ((Stage = 'done') and (State = 'ready')) then
          Break;
      end else
        { Keeps the window responsive while the first report is on its way. }
        PreparePage.SetProgress(PreparePage.ProgressBar.Position, 100);
      if Quiet > StalePolls then begin
        Log('The download stopped reporting; leaving it to the app.');
        State := 'failed';
        Break;
      end;
    until False;
  finally
    PreparePage.Hide;
  end;
  Log('Prepare ended: stage=' + Stage + ' state=' + State + ' code=' + Code + ' error=' + Error);
  if State = 'cancelled' then
    PrepareNote := 'The speech model download was paused. {#AppName} continues it before your first transcription.'
  else if Code = 'no_space' then
    PrepareNote := 'There was not enough free disk space for the speech model (about 4 GB). Free some space; {#AppName} downloads it before your first transcription.'
  else if State = 'failed' then begin
    if Stage = 'gpu' then
      PrepareNote := 'The speech model is ready. The GPU libraries could not be downloaded, so {#AppName} transcribes on the processor for now.'
    else
      PrepareNote := 'The speech model could not be downloaded now. {#AppName} tries again before your first transcription.';
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then begin
    if ModelDownloadSkipped then
      Log('Speech model download skipped (/NOMODEL=1)')
    else
      RunPrepare;
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if (CurPageID = wpFinished) and (PrepareNote <> '') then
    WizardForm.FinishedLabel.Caption := WizardForm.FinishedLabel.Caption + #13#10#13#10 + PrepareNote;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  Home, What: String;
begin
  if CurUninstallStep = usUninstall then
    StopUpshot;
  if (CurUninstallStep <> usPostUninstall) or UninstallSilent then
    Exit;
  Home := ExpandConstant('{localappdata}\upshot');
  if not DirExists(Home + '\models') and not DirExists(Home + '\cuda') then
    Exit;
  What := 'the speech model (about 3 GB)';
  if DirExists(Home + '\cuda') then
    What := 'the speech model and the GPU libraries (about 5 GB)';
  if MsgBox('Also remove ' + What + '?' + #13#10#13#10 +
      'Your recordings, transcripts and settings are kept either way. Keep the model if you may reinstall {#AppName}.',
      mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES then begin
    DelTree(Home + '\models', True, True, True);
    DelTree(Home + '\cuda', True, True, True);
  end;
end;
